### ISSUE TITLE
Cache not updating?

### ISSUE THREAD

**Issue by Memnarch** [schme16/gitcdn.xyz#12]
Hi,
I just tried out your system. It says that it needs round about 2 ours for changes to be distributed(as the cache is held for those 2 hours).

~6Hours ago i hit the following link:
https://gitcdn.xyz/repo/Memnarch/TestRepository/master/info.json

Then i commited a change(directly from within the Github page) changing first_version from v1.2 to v1.22, as you can see here:
https://raw.githubusercontent.com/Memnarch/TestRepository/master/info.json

however, the link above has not yet been updated. I am a bit confused right now.

**Comment by Memnarch** [comment]
As of now, it has updated. But that took quite long(i don't know when it did, just noticed this morning)

**Comment by schme16** [comment]
Thanks for the heads up! I'll look into what's happening!

**Comment by noo-zh** [comment]
@Memnarch I think this is solved with the last commit. You need to use tags (it means don't use links to master branch), for example:

- https://gitcdn.xyz/repo/Memnarch/TestRepository/v1.2/info.json
- https://gitcdn.xyz/repo/Memnarch/TestRepository/v1.1/info.json

Everytime you update something, you should increase a version of your project. This is awesome also in case if you need to support more versions (backward compatibility).

**Comment by Memnarch** [comment]
Thanks

**Comment by noo-zh** [comment]
@Memnarch Yes, there is no change for a master branch.

**Comment by Memnarch** [comment]
Thank you, this will already help me. In case the content of a Tag is updated, it took 1-2h to update, right?
Btw the example on the Frontpage still shows an example to get the latest commit. So if that is not updated, shouldn't the example change?

**Comment by RubyistCTRLDYT** [comment]
what about https://min.gitcdn.link/repo, 
I use .link and I commited a change ，
It been a day and it still not update，  
but when I use https://gitcdn.xyz/repo/
It take about 2 hour to Update，
and indeed my link in https://gitcdn.xyz/repo/ is already Updated
but https://min.gitcdn.link/repo,.....   is still point to the old file
So how could update the link on https://min.gitcdn.link/repo,.....

**Comment by schme16** [comment]
It's correct that the min.gitcdn.* urls cache for as long as possible, in order to use the latest you just visit the normal link, get what it redirected to, and add `min.` to the front of the url

**Comment by rhpo** [comment]
Hi @Memnarch, i don't work here, but this happens because the browser cache, to fix that, add a random (any) search query string to the cdn link,

E.x: https://gitcdn.link/cdn/rhpo/life.js/main/src/life.min.js  => https://gitcdn.link/cdn/rhpo/life.js/main/src/life.min.js?foo=bar
Where ``foo=bar`` is a random search query.

That should fix it, have a great day!
