### ISSUE TITLE
Certificate problem

### ISSUE THREAD

**Issue by gustavocampos** [schme16/gitcdn.xyz#53]
An invalid certificate problem broke our systems...

**Comment by Anthchirp** [comment]
certificate for https://gitcdn.link/ only covers `*.herokuapp.com, herokuapp.com`

**Comment by Anthchirp** [comment]
https://gitcdn.xyz is unaffected

**Comment by gustavocampos** [comment]
I've just changed to cloudfare... seems more reliable, right?

**Comment by schme16** [comment]
Hey all, I'm in contact with cloudflares support staff; looks like the .link address got pinged due to someone trying to host a phishing site from github, using the .link domain.

I've banned that repo and user, just waiting for confirmation that cloudflare have cleared the strike. 

Stay tuned!

**Comment by schme16** [comment]
Issue should be solved now, leaving this open a few days to makes sure

**Comment by BeanVegan1969** [comment]
Hi schme16,

Seem to still be seeing cert issues for an Angular resource when reaching out here:

https://cdn.gitcdn.link/cdn/angular/bower-material/v1.1.3/angular-material.js

I'm a bit unfamiliar with our system using this resource, but troubleshot my way over here. Just wanted  to mention we're still seeing these cert errors. Let me know if I can provide any further information or assist in any other way.

**Comment by schme16** [comment]
That's strange, it should have already gone back to normal- I'll contact cloudflare and get their assistance tracking this issue!
In the mean time, you should be able to switch to the gitcdn.xyz version (just switch .link to .xyz) and be back in action.

Will keep everyone posted!

**Comment by BeanVegan1969** [comment]
Thanks schme16! Things are looking good again on our side now. If I see any other unusual behavior I'll let you know. Appreciate the quick help on all this!

**Comment by schme16** [comment]
Awesome! I did also get word from CloudFlare that everything is back the
way is should be.

Sorry to all effected by this outage!!

**Comment by FranklinYu** [comment]
@BeanVegan1969 I am already able to access the URL you posted. This issue is fixed?

**Comment by schme16** [comment]
Yeah, looks like I can close it off now.
